import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/Navbar";

export default function Home() {
  return (
    <>
      <Head>
        <title>News Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/favicon-32x32.png" />
      </Head>

      <Navbar />
      <main className="p-4">
      <div
          class="h-[35%] c-md:h-full w-full c-md:w-3/6 bg-cover bg-center rounded-t-lg c-md:rounded-t-none c-md:rounded-l-lg bg-mobile c-md:bg-desktop"
        ></div>
      </main>

      <footer className="flex justify-center items-center gap-4 p-2 w-full h-12 border-t absolute bottom-0">
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>

        <p>
          Coded by{" "}
          <a
            className="text-blue-500"
            href="https://github.com/tiburciohugo"
            target={"_blank"}
            rel={"noopener noreferrer"}
          >
            Hugo Tiburcio
          </a>
        </p>
      </footer>
    </>
  );
}
