import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Navbar from "../components/Navbar";
import { posts } from "../data/posts.js";
import { articles } from "../data/articles";

export default function Home() {
  return (
    <div className="lg:flex lg:justify-center">
      <Head>
        <title>News Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/favicon-32x32.png" />
      </Head>

      <Navbar />
      <main className="p-4 h-full w-screen max-w-6xl mt-6">
        <section className="c-md:flex c-md:gap-6">
          <div className="w-full c-md:w-8/12">
            <div class="h-[15rem] c-md:h-3/6 w-full bg-cover bg-center bg-mobile c-md:bg-desktop p-4 mt-14"></div>
            <div
              className="md:flex md:gap-6 mt-4
            "
            >
              <h1 className="text-4xl md:text-5xl lg:text-6xl text-very-dark-blue text-left font-bold w-[90%] md:w-3/6 mt-2">
                The Bright Future of Web 3.0?
              </h1>
              <div className="md:flex md:flex-col md:w-3/6">
                <p className="text-dark-grayish-blue text-[1rem] font-semibold mt-2">
                  We dive into the next evolution of the web that claims to put
                  the power of the platforms back into the hands of the people.
                  But is it really fulfilling its promise?
                </p>
                <button className="tracking-[.3rem] w-[10.5rem] h-10 bg-soft-red text-white font-semibold text-xs py-2 mt-8 lg:mt-6 hover:bg-very-dark-blue">
                  READ MORE
                </button>
              </div>
            </div>
          </div>
          <aside className="bg-very-dark-blue mt-12 h-full c-md:w-4/12 flex flex-col py-4 px-6 md:mt-14">
            <h2 className="text-soft-orange text-4xl font-bold">New</h2>
            {posts ? (
              <div>
                {posts.map((post) => (
                  <div
                    className="py-4 border-t-[1px] border-dark-grayish-blue first:border-none"
                    key={post.id}
                  >
                    <Link href={`/posts/${post.id}`}>
                      <h4 className="text-white text-lg font-bold mt-4 hover:text-soft-orange">
                        {post.title}
                      </h4>
                    </Link>
                    <p className="text-grayish-blue text-sm my-2">
                      {post.content}
                    </p>
                  </div>
                ))}
              </div>
            ) : (
              <div>
                <p className="text-grayish-blue font-semibold mt-4">
                  loading...
                </p>
              </div>
            )}
          </aside>
        </section>

        <section>
          {articles ? (
            <div className="mt-10 md:mt-14 flex flex-col md:flex-row gap-4 items-center h-fit w-full">
              {articles.map((article) => {
                return (
                  <div
                    key={article.id}
                    className="flex gap-3 md:gap-2 h-full w-full"
                  >
                    
                      <Image
                        className="object-cover"
                        src={article.image}
                        width={90}
                        height={90}
                        alt={article.title}
                      />
                    
                    <div
                      key={article.id}
                      className="flex flex-col justify-center items-start gap-y-2  md:gap-0 lg:gap-y-2 md:w-4/6 lg:w-full h-full px-2 md:px-0 md:ml-4"
                    >
                      <h2 className="text-grayish-blue text-3xl font-bold">
                        {article.number}
                      </h2>
                      <Link href={`/articles/${article.id}`}>
                        <h4 className="text-very-dark-blue text-md font-bold hover:text-soft-red">
                          {article.title}
                        </h4>
                      </Link>
                      <p className="text-dark-grayish-blue text-sm font-semibold w-5/6">
                        {article.content}
                      </p>
                    </div>
                  </div>
                );
              })}
            </div>
          ) : null}
        </section>
      </main>

      {/* <footer className="flex justify-center items-center gap-4 p-2 w-full h-12 border-t absolute bottom-0">
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>

        <p>
          Coded by{" "}
          <a
            className="text-blue-500"
            href="https://github.com/tiburciohugo"
            target={"_blank"}
            rel={"noopener noreferrer"}
          >
            Hugo Tiburcio
          </a>
        </p>
      </footer> */}
    </div>
  );
}
