import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/Navbar";

export default function Home() {
  return (
    <>
      <Head>
        <title>News Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/favicon-32x32.png" />
      </Head>

      <Navbar />
      <main className="p-4 h-full w-screen mt-6">
        <section>
          <div class="h-[15rem] w-[full] md:w-4/6 bg-cover bg-center bg-mobile md:bg-desktop p-4 mt-14"></div>
          <h1 className="text-4xl text-very-dark-blue text-left font-bold w-[90%] mt-4">
            The Bright Future of Web 3.0?
          </h1>
          <p className="text-dark-grayish-blue text-[0.969rem] md:text-lg font-semibold mt-4">
            We dive into the next evolution of the web that claims to put the
            power of the platforms back into the hands of the people. But is it
            really fulfilling its promise?
          </p>
          <button className="tracking-[.3rem] w-[12rem] md:w-[15rem] h-12 bg-soft-red text-white font-semibold text-xs md:text-lg py-2 mt-6">
            READ MORE
          </button>
        </section>

        <section className="bg-very-dark-blue mt-12 h-[30rem] flex flex-col p-4">
          <h2 className="text-soft-orange text-2xl font-bold">New</h2>
        </section>
  
      </main>

      {/* <footer className="flex justify-center items-center gap-4 p-2 w-full h-12 border-t absolute bottom-0">
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>

        <p>
          Coded by{" "}
          <a
            className="text-blue-500"
            href="https://github.com/tiburciohugo"
            target={"_blank"}
            rel={"noopener noreferrer"}
          >
            Hugo Tiburcio
          </a>
        </p>
      </footer> */}
    </>
  );
}
